### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by lijiee** [intsig171/SmartCodable#1]
<img width="1267" alt="image" src="https://github.com/intsig171/SmartCodable/assets/17916798/5d42c36c-33c2-484c-a922-d949bd8dc91e">
            guard let tempKey = userKey, let originDict = superDe.userInfo[tempKey] as?[String : Any] else {} 
这行代码有问题，originDict返回的是一个json字符串，所以解析失败

**Comment by intsig171** [comment]
已解决。
