### ISSUE TITLE
SmartAny的问题

### ISSUE THREAD

**Issue by ET-LINK** [intsig171/SmartCodable#10]
我用主页说明的方式使用SmartAny代码得出的peel值都是false, 请验证一下

**Comment by intsig171** [comment]
感谢反馈，确实是有问题。我正在排查修复。

**Comment by ET-LINK** [comment]
是否有计划添加[String:SmartAny] 形式的反序列化, 有些需求是对已经反序列化成[String:SmartAny]的进行二次反序列化, 在HandyJSON时使用[String: Any]是可行的

**Comment by intsig171** [comment]
是否可以提供具体的案例。让我充分理解你的需求。

**Comment by intsig171** [comment]
SmartAny 解析错误的问题已经修复。请更新版本为V3.0.5. 

关于[String:SmartAny] 的反序列化，可以调用.peel 属性进行。 如果我误解了你的诉求，请告知。

**Comment by ET-LINK** [comment]
> SmartAny 解析错误的问题已经修复。请更新版本为V3.0.5.
> 
> 关于[String:SmartAny] 的反序列化，可以调用.peel 属性进行。 如果我误解了你的诉求，请告知。
没问题了, 是昨天的BUG让我有此疑惑, 确实直接用.peel就行了
