### ISSUE TITLE
如何将[String:Any] 转换为[String:SmartAny]

### ISSUE THREAD

**Issue by BestKai** [intsig171/SmartCodable#12]
比如Mode 有一个属性A是[String:SmartAny]，后续逻辑需要重新将[String:Any]赋值给A，应该怎样处理呢？

**Comment by intsig171** [comment]
本周内，我提供一个加壳的方法。 将 [String:Any] 加壳为 [String:SmartAny]，然后赋值给属性A。

**Comment by BestKai** [comment]
Any转SmartAny 也有这种场景

**Comment by intsig171** [comment]
好的。 三种场景 Any转SmartAny ，[Any]转[SmartAny], [String:Any] 转 [String:SmartAny]

**Comment by intsig171** [comment]
最新的V3.2.0 已支持。
