### ISSUE TITLE
字符串的Model化相关问题

### ISSUE THREAD

**Issue by linkjd** [intsig171/SmartCodable#15]
您好，
字符串的Model可以将value为String类型的json转换为对应的model，但如果json的最外层是数组，似乎无法成功转换为对应的model，例如：
let dict: [String: Any] = [
    "hobby": "{\"name\":\"sleep\"}",
]
如上这种情况可以成功转换为model，
而如果是如下这种情况，似乎无法成功转换为model
let dict: [String: Any] = [
    "hobby": "[{\"name\":\"sleep\"}]",
]

在阅读源码后发现如下地方是产生问题的原因：
![WechatIMG257](https://github.com/intsig171/SmartCodable/assets/12538981/4623462a-aaf1-458f-b6c4-a00842ea30ac)

由于此时T为数组类型的model（[Model].type），而value为string，所以会return nil，不会继续解析。
所以我在这里加了一个判断，才得以完成之后的解析，最后成功转换为对应的model。
![WechatIMG258](https://github.com/intsig171/SmartCodable/assets/12538981/2d7186e6-b3cd-4c08-9972-588dd4c2a0d8)
所以此问是想了解一下，这样的改动会不会对整体功能有影响，或者影响到其他相关功能呢？

**Comment by intsig171** [comment]
稍等，我详细看看。

**Comment by intsig171** [comment]
你的解决办法是合理的。if let _ = [] as? T  的判断之后只有 模型中属性是数组类型才会进入。所以只会影响这种情况。 下个版本修复该问题，预计本周五下班前。
