### ISSUE TITLE
AnyHashable

### ISSUE THREAD

**Issue by TttGggVv** [intsig171/SmartCodable#17]
var dps : [AnyHashable : SmartAny] = [:]
AnyHashable 这个类型需要帮着支持下，或者怎么解决

**Comment by TttGggVv** [comment]
类型不能换

**Comment by intsig171** [comment]
字典的key，除了String还有其他情况么？ 
AnyHashable 没有遵循Codable，应该是没法支持的。 不过我可以根据使用场景，进行支持。比如新增一个SmartKey用来作为key的类型。

**Comment by TttGggVv** [comment]
这个不用了
