### ISSUE TITLE
为啥不支持继承？

### ISSUE THREAD

**Issue by TttGggVv** [intsig171/SmartCodable#19]
太多场景都是继承的

**Comment by intsig171** [comment]
请看： 
![image](https://github.com/intsig171/SmartCodable/assets/87351449/77954260-2f74-427d-ae2d-3aa9a015c57a)

继承需要自己重写init(decoder:)方法。 demo中有提供。

**Comment by TttGggVv** [comment]
这个能不能支持一下？强烈要求支持一下

**Comment by intsig171** [comment]
我们开源团队也非常想支持。 目前还没有可行性的方案。 可以通过协议的方式实现。 这个协议就当作基Model，子model遵循这个协议，自动拥有了协议中的属性。

**Comment by intsig171** [comment]
请查看readme 中的  #suggest 2 像HandyJSON一样支持继承关系的解析

**Comment by intsig171** [comment]
protocol Base {
    var name: String { get set }
    var age: Int { get set }
}

struct SubModel1: SmartCodable, Base {
    var name: String = ""
    var age: Int = 0
} 
可以使用协议完成相同的属性的声明，减少工作量。
