### ISSUE TITLE
建议完善的单元测试

### ISSUE THREAD

**Issue by saddit** [intsig171/SmartCodable#23]
基础库的稳定性极为重要，这个项目缺少完整单元测试，无法确定是否具备生产可用的条件，建议召集社区力量完善单元测试，以100%代码覆盖为目标建设。

**Comment by intsig171** [comment]
感谢你的反馈。
目前SmartCodable的单元测试流程是这样的： 
1. 开发人员的自测，demo中提供的穷举的各种场景，都会验证一遍。
2. SmartCodable也用在公司的项目中，业务团队会进行功能层面的测试。
3. SmartCodable每次版本发布都会同步到QQ交流群（群号：865036731）做线上验证。
4. SmartCodable的大版本更新，会发布beta版本，进行公测，根据功能大小，公测时间2～4周不等。

欢迎大家参与SmartCodable的开发&测试建设，如有意向请加QQ交流群（群号：865036731）。

**Comment by chengongwen** [comment]
由于HandyJSON在xcode15.3报错且已经不更新维护了， 我已经用SmartCodable平替了HandyJSON，感觉性能很棒，希望大佬持续更新，再次感谢！！！

**Comment by intsig171** [comment]
欢迎加入QQ交流群（群号：865036731）。 会及时更新相关的信息。

**Comment by Liyongcong** [comment]
865036731搜索不到群。。。

**Comment by intsig171** [comment]
![wecom-temp-620761-86b1f8567cef3c088c90f79458bf1d62](https://github.com/intsig171/SmartCodable/assets/87351449/402507c0-f9cf-4219-b387-e1deb2312440)
