### ISSUE TITLE
Int32等接收，转化不了String类型的int值

### ISSUE THREAD

**Issue by guoke3418857** [intsig171/SmartCodable#25]
后端返回了一个int值的字符串，如"11111111"，此时我用Int32/Int16/Int64/UInt/Uint16/UInt32等类型去接收，会转化不出来，只能使用Int去接收。能否兼容一下Int的其它类型。

**Comment by intsig171** [comment]
OK,没问题。 预计今晚提交新版本V3.4.5版本，对该case兼容。

**Comment by intsig171** [comment]
V3.4.5 已发布。 需要注意类型的长度。比如Int8范围在-127～128之间。
