### ISSUE TITLE
日志错误打印

### ISSUE THREAD

**Issue by developerjet** [intsig171/SmartCodable#26]
我加载的json数据正常，且有需要解析的字段，SmartLog error提示 错误类型: '找不到键的错误'

```    
private func loadCircleData() {
        
        guard let path = Bundle.main.path(forResource: "circle_data", ofType: "json") else { return }
        
        do {
            let data = try Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe)
            let jsonArray = try JSONSerialization.jsonObject(with: data, options: .mutableLeaves)
            if let jsonArray = jsonArray as? [[String: Any]] {
                if let modelList = [TYCircleHomeListModel].deserialize(array: jsonArray) {
                    let randomList = modelList.shuffled().compactMap { $0 }
                    
                    if (self.pageIndex == 1) {
                        self.dataSource = randomList
                    }
                    
                    
                    if (self.pageIndex > 1) {
                        if (self.pageIndex >= 10) {
                            self.endRefreshing()
                            self.tableView.mj_footer?.state = .noMoreData
                            return
                        }
                        
                        self.dataSource.append(contentsOf: randomList)
                    }
                    
                    DispatchQueue.main.asyncAfter(deadline: .now()+1.25) {
                        self.tableView.reloadData()
                        self.endRefreshing()
                    }
                }
            }
        } catch {
            print("Error parsing JSON: \(error)")
        }
    }
```

============= 💔 [SmartLog Error] 💔 =============
错误类型: '找不到键的错误'
模型名称：Array<TYCircleHomeListModel>
数据节点：Index 5
属性信息：videoUrl
错误原因: No value associated with key CodingKeys(stringValue: "videoUrl", intValue: nil) ("videoUrl").
==================================================

**Comment by intsig171** [comment]
是否可以提供测试用例。

**Comment by developerjet** [comment]
> 是否可以提供测试用例。

[circle_data.json](https://github.com/intsig171/SmartCodable/files/15450145/circle_data.json)

**Comment by developerjet** [comment]
> > 是否可以提供测试用例。
> 
> [circle_data.json](https://github.com/intsig171/SmartCodable/files/15450145/circle_data.json)

json数据已提供

**Comment by intsig171** [comment]
Model也给一下，最好能给个可以运行的demo。

**Comment by developerjet** [comment]
> Model也给一下，最好能给个可以运行的demo。

`import SmartCodable

struct TYCircleHomeListModel: SmartCodable {
    
    /// 发帖时间
    var date: String = ""
    
    /// 发帖内容
    var content: String = ""
    
    /// 用户昵称
    var nickname: String = ""
    
    /// 头像URL
    var avatarUrl: String = ""
    
    /// 图片数组
    var images: [String] = []
    
    /// 视频URL
    var videoUrl: String = ""
    
    /// 数据类型1：图片   2：视频
    var sourceType: Int = 1
}

`

**Comment by intsig171** [comment]
![image](https://github.com/intsig171/SmartCodable/assets/87351449/bad34bb9-ac1d-4aa3-8e39-8ad58e8ebe0c)
你Model中定义了7个需要解析的属性，数据中就只有4个字段，缺失了videoUrl，avatarUrl，sourceType。 日志给出提示是合理的。

**Comment by developerjet** [comment]
> ![image](https://private-user-images.githubusercontent.com/87351449/333944059-bad34bb9-ac1d-4aa3-8e39-8ad58e8ebe0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODE3MDAsIm5iZiI6MTcxNjc4MTQwMCwicGF0aCI6Ii84NzM1MTQ0OS8zMzM5NDQwNTktYmFkMzRiYjktYWMxZC00YWEzLThlMzktOGFkNThlOGViZTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzNDMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NmJiMTRiMWZjOTIwYTViN2NiOWRhMjMxMjQyMjgyOGRjMTAwOWZkMDg3Y2RlYjNlMDMzMzc3YTdjNDY3ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l9RiWWPl5cOjrhTwhBO6m3awsmh0XT-IL5bo7yCZOPw) 你Model中定义了7个需要解析的属性，数据中就只有4个字段，缺失了videoUrl，avatarUrl，sourceType。 日志给出提示是合理的。

好的，谢谢了。这种提示是正向的，但感觉有些强提示了，哈哈

**Comment by intsig171** [comment]
你可以更改日志的debug模式为warning。这样就只会提示类型不匹配的日志。

**Comment by developerjet** [comment]
> 你可以更改日志的debug模式为warning。这样就只会提示类型不匹配的日志。

好的，我调整下。
