### ISSUE TITLE
可以支持一个类或者结构体中添加这个字典来接受后台的数据吗

### ISSUE THREAD

**Issue by Xcode123456** [intsig171/SmartCodable#27]
<img width="974" alt="WeChat3bed895a5b32ab2830244bf479492d29" src="https://github.com/intsig171/SmartCodable/assets/28332571/cd073691-c173-4c93-9b69-9cd5f6b0bf32">

我自己实现了一个，但是使用起来非常麻烦，还需要各种转换，大佬辛苦看下

**Comment by intsig171** [comment]
改成[String: SmartAny] 类型。 注意使用的时候需要解包（.peel）。Any是不支持Decodeable的，所以自定义了SmartAny类型参与解析。 demo样例中有使用说明。

**Comment by intsig171** [comment]
SmartAny类型已优化为SmartAny属性包装器。 请查看最新的readme文档。
