### ISSUE TITLE
请问是否支持忽略key的大小写

### ISSUE THREAD

**Issue by lijianontheway** [intsig171/SmartCodable#30]

**Comment by intsig171** [comment]
目前全局的key映射策略只支持首字母转大小写，蛇形转驼峰。

**Comment by intsig171** [comment]
局部策略（Model级） 重写mappingForKey方法可以自定义映射。

**Comment by lijianontheway** [comment]
> 目前全局的key映射策略只支持首字母转大小写，蛇形转驼峰。

收到，感谢

**Comment by intsig171** [comment]
你可以加QQ群，提你的需求，如果有适用场景，我们会考虑添加该功能。 
QQ群在readme的最底部。
