### ISSUE TITLE
4.0.4版本解析结果不符合期望

### ISSUE THREAD

**Issue by ad0ma** [intsig171/SmartCodable#36]
struct Room: SmartCodable {
    var game: Game?
}

struct Game: SmartCodable {}

这种结构下，当json返回room结构中的game为null时。
3.4.5版本的game为null。
4.0.4版本的game不为null。

**Comment by intsig171** [comment]
麻烦提供一下对应的数据。

**Comment by ad0ma** [comment]
补充4.0.3.1也是正常的

**Comment by ad0ma** [comment]
{
  "game" : null
}

**Comment by intsig171** [comment]
方便加一下QQ群【865036731】么？  我想了解一下你的需求。 为什么会有空模型的解析场景。

**Comment by intsig171** [comment]
V4.1.0 版本已优化该问题。
