### ISSUE TITLE
moya response is data

### ISSUE THREAD

**Issue by Coder-Miao** [intsig171/SmartCodable#4]
open func decode<T>(_ type: T.Type, from data: Data) throws -> T where T : Decodable 
在moya请求返回直接是data, codable亦支持

你可能需要增加 public static func deserialize(data: Data?) -> Self?

**Comment by intsig171** [comment]
感谢使用，最新的版本（1.2.5）已经支持data解析。 如果感觉不错，请点个star，让更多的人看到。
