### ISSUE TITLE
使用UInt32等类型来接收字符串类型的时间戳，解析出来的结果是nil。

### ISSUE THREAD

**Issue by realLam** [intsig171/SmartCodable#41]
微信支付的时间戳类型是UInt32，后台返回是的字符串。导致微信支付时报错”签名认证失败“。为了解决问题，我暂时用TimeInterval替换 UInt32，替换后微信支付正常。

struct Model: SmartCodable {
    var timestamp: UInt32?
}

let dic: [String : Any] = [
    "timestamp": "1721721316"
]

let model = Model.deserialize(from: dic)
model.timestamp 打印出来为nil。

**Comment by intsig171** [comment]
![image](https://github.com/user-attachments/assets/095a3a21-cf06-43a1-8115-6c7442fd55e8)
我这边验证没问题。 请确实是否使用了最新版本。

**Comment by realLam** [comment]
确实是版本问题，从3.4.5升级到4.1.2，正常解析了！
