### ISSUE TITLE
mapkey 和 value支持resultBuilder

### ISSUE THREAD

**Issue by TmFtZW9mR2l0aHVi** [intsig171/SmartCodable#42]
类似这样：
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/7141895f-a086-41f5-a55a-63aabc4e4a73">
可以不用写中括号和逗号

旧调用和重写的地方都不需要修改能同时兼容：
<img width="780" alt="image" src="https://github.com/user-attachments/assets/7192507e-ae5a-40fa-8bb0-24ef9f19b6b9">

**Comment by intsig171** [comment]
可以加QQ讨论一下么：865036731
