### ISSUE TITLE
是否有机会获取到解析前的数据

### ISSUE THREAD

**Issue by luyud** [intsig171/SmartCodable#46]
例如在 `didFinishMapping()` 或其他方法中是否可以获取到 原始的 json(dictionary， array等)，
类似YYModel中的 `- (BOOL)modelCustomTransformFromDictionary:(NSDictionary *)dic` 方法中的`dic`

**Comment by intsig171** [comment]
获取不到。不过你可以使用model.toDict方法 转成json数据

**Comment by luyud** [comment]
关于`SmartEncodable` 的 `toDictionary()` 方法， 在decode的时候设置了options， `.date(.millisecondsSince1970)`, 即从毫秒时间戳转换成了`Date`.
但是在Encode时我没找到在哪里设置相同的options可以将`Date`还原成毫秒时间戳， 我看到encode代码部分是有 `case .millisecondsSince1970:` 的。
请问如何做才能还原`Date`到时间戳呢？

**Comment by intsig171** [comment]
你可以先用mappingForValue解决问题。 全局设置的参数，我下午看看，再回复你。 注意看看toDictionary的默认参数。

**Comment by luyud** [comment]
好的，谢谢, 这是我的encode设置
```
let dic = model.toDictionary(useMappedKeys: true)
```

以及decode时
```
extension SmartDecodable {
    static func decode(_ from: [String: Any]?) -> Self? {
        deserialize(from: from, options: [.date(.millisecondsSince1970), .key(.fromSnakeCase)])
    }
}
```

**Comment by intsig171** [comment]
哥们方便加一下QQ群么？ 865036731

**Comment by intsig171** [comment]
该问题已在4.1.11-beta.4版本优化，近期会发布正式版本。

**Comment by intsig171** [comment]
V4.2.0正式版本已发布。
