### ISSUE TITLE
既然都支持UIColor这种对象转色值，何不兼容一下CloutKit的CKAsset转路径字符串？

### ISSUE THREAD

**Issue by PassLock-App** [intsig171/SmartCodable#48]
我看wiki没搜到CKAsset，也许已经支持了？如果没有，希望可以支持！star先点上👍

**Comment by intsig171** [comment]
这个类型不常使用吧?  可以提供一下使用场景，我这边考虑一下。 实现起来应该不难，跟URL的实现逻辑一致即可。

**Comment by intsig171** [comment]
CKAsset 是苹果的 CloudKit 框架中的一个类，用于处理大文件或二进制数据（如图片、视频、音频文件等）的存储。 这个数据类型使用的较少，并且需要引入CloutKit框架，暂时不支持该类型的解析。

**Comment by PassLock-App** [comment]
公司项目一般用不到，但独立开发者100个里面有90个人用。它是CloudKit里面的一个文件对象。比如保存一个文件（图片、视频等），保存成功后得到一个CKAset对象，它里面就一个本地路径的URL。可以在多设备同步。这样独立开发者的项目都不需要自己的服务器了，所以还是很受欢迎的。只是没法跨平台，所以公司项目都不用它。


intsig171 ***@***.***>于2024年9月27日 周五下午5:43写道：

**Comment by intsig171** [comment]
ok，我会在本周搞定它。

**Comment by PassLock-App** [comment]
不着急。绝对路径如果不好搞就算了，我们可以继续过滤它，因为一般取值也是一个一个取，也挺坑的。

intsig171 ***@***.***>于2024年10月8日 周二下午5:48写道：

**Comment by intsig171** [comment]
是否可以下载demo工程，提供一个你现在的场景的使用示例给我。 可以加QQ群： 865036731

**Comment by PassLock-App** [comment]
现在开发的项目没用它了，以前的项目还是HandyJson，还没更新成你们的😭


intsig171 ***@***.***>于2024年10月8日 周二下午5:53写道：

**Comment by intsig171** [comment]
你可以下载github上的demo工程，写个你的需求示例。 
我要完全了解你的需求。

**Comment by PassLock-App** [comment]
好的

intsig171 ***@***.***>于2024年10月8日 周二下午6:17写道：

**Comment by mancongiOS** [comment]
大概什么时候提供。

**Comment by intsig171** [comment]
大概什么时候提供

**Comment by intsig171** [comment]
未提供场景，暂不支持。
