### ISSUE TITLE
有没有计划对泛型进行支持

### ISSUE THREAD

**Issue by AmadeusSys** [intsig171/SmartCodable#5]
在网络接口的封装中有个典型的场景是封装上级通用model例如下图，这个场景下使用泛型来动态定义model中的业务成员类型
<img width="475" alt="image" src="https://github.com/intsig171/SmartCodable/assets/25811397/a461000d-a1ca-4010-8308-26d5adaedd19">

刚才试了下，好像默认不支持泛型的嵌套解析，自定义实现了一下decoder，如果json字符串不对就进断言里了，不知道咋能避免这个难问题

**Comment by intsig171** [comment]
如有有场景的需要，会支持泛型。

不能完全理解你的需求。方便提供一下你的演示代码么？ 或者加一下QQ群：865036731

**Comment by intsig171** [comment]
![image](https://github.com/intsig171/SmartCodable/assets/87351449/d6d46e0f-cb8c-4363-8672-9ea042aa2a36)

经过验证，目前是支持的。 如有疑问可继续沟通， 或者加一下QQ群：865036731。
