### ISSUE TITLE
V4.2.0-V4.2.1版本自定义value解码结果会不正确

### ISSUE THREAD

**Issue by cultlee** [intsig171/SmartCodable#50]
<img width="786" alt="image" src="https://github.com/user-attachments/assets/41215284-dc2a-42c1-ac13-3920d027a244">
转出来的结果为空数组

**Comment by intsig171** [comment]
是否可以提供更详细的信息？ 你的数据是什么样子的？

**Comment by intsig171** [comment]
如果你使用的数据是： // "B3322,A7584,C2554,E9987,D1485,F8877, 2" 请注意 2前面有一个空格。         guard let comps = (value as? String)?.split(separator: ",").compactMap({ "\($0)" }),
              let index = Int(comps.last ?? "") else {
            return result
        }
