### ISSUE TITLE
你好，如何实现JSON转Model的时候，同时往UserDefaults中存，取值的时候，通过UserDefaults取啊？

### ISSUE THREAD

**Issue by xiaoyao20084321** [intsig171/SmartCodable#54]
你好，如何实现JSON转Model的时候，同时往UserDefaults中存，取值的时候，通过UserDefaults取啊？

**Comment by intsig171** [comment]
UserDefaults 不是一个类型，是一种存储方式。 这个属于业务的范畴了。 根据业务的不同，有不同的方式。 比如你可以在 解析结束的时候存下。

**Comment by xiaoyao20084321** [comment]
那取的时候，如何取UserDefaults里面的值呢？ 比如我现在登录成功后，获得到的json通过咱们这个库转成model，然后也在解析成功的时候存到了UserDefaults值，此时我关闭app，重新打开，如何通过mode.属性，然后就获取到UserDefaults值了
我现在是这么做的，但是我现在都是手动来取出json来赋值，我想用咱们的这个自动来给属性赋值
<img width="635" alt="image" src="https://github.com/user-attachments/assets/9283583a-efda-4942-a7e0-d42647ebf9a4">
<img width="1046" alt="image" src="https://github.com/user-attachments/assets/1be1d817-c412-45e2-b7aa-eaaaeb5189f2">
<img width="873" alt="image" src="https://github.com/user-attachments/assets/fdf3399e-c452-417b-8075-ab2b82585afb">
