### ISSUE TITLE
你好，创建model继承SmartCodable时候，model里面的属性支持使用官方Combine框架里面的@Published嘛

### ISSUE THREAD

**Issue by xiaoyao20084321** [intsig171/SmartCodable#55]
你好，创建model继承SmartCodable时候，model里面的属性支持使用官方Combine框架里面的@Published嘛？
如下面
class UserModel: SmartCodable {
    @Published var age: Int?
    @Published var name: String?
}

然后使用的时候，UserModel.deserialize(from: json)后，就可以自动更新UI嘛？

**Comment by faimin** [comment]
为什么不自己试一下呢

**Comment by intsig171** [comment]
不直接支持官方的published，需要使用SmartPublished。 具体可以看demo中的示例

**Comment by xiaoyao20084321** [comment]
好的，多谢
