### ISSUE TITLE
请问下，模拟器支持吗？因为用到一些第三方，只能在模拟器运行，但是xcode运行报错

### ISSUE THREAD

**Issue by CoderST** [intsig171/SmartCodable#58]
![image](https://github.com/user-attachments/assets/2a785c9f-3a17-4ccc-be17-ae1d04a39523)

**Comment by intsig171** [comment]
![image](https://github.com/user-attachments/assets/0f04e4ca-4627-4a62-95cb-3fa561be4ee0)
我这边的模拟器运行是正常的。 你看看你的工程配置。  或者下载github上的工程运行看看。
