### ISSUE TITLE
增加对泛型的兼容

### ISSUE THREAD

**Issue by LostVan** [intsig171/SmartCodable#59]
如图所示，HandyJSON支持任意类型的泛型，您的框架能否增加兼容~
![image](https://github.com/user-attachments/assets/4d5045da-5d69-4a26-b940-54f95cd64ed9)
![image](https://github.com/user-attachments/assets/80eb5f02-9f47-48ab-bded-fe90d2e0ebde)

**Comment by intsig171** [comment]
任意类型T 必须遵循Codable。
