### ISSUE TITLE
能不能完善demo中实际网络请求数据业务中data可能是其他任意类型，比如string ， nul ， int等等

### ISSUE THREAD

**Issue by TML007** [intsig171/SmartCodable#60]
![image](https://github.com/user-attachments/assets/4fdb64f4-d21b-40cf-8f6d-e1f148822818)

**Comment by intsig171** [comment]
![image](https://github.com/user-attachments/assets/c2fc97a9-3c8a-4dad-8b8c-7f1450cb4ad1)
改变泛型的类型即可。 代码已上传。
