### ISSUE TITLE
在iOS 12上，数据转换会有问题

### ISSUE THREAD

**Issue by jackmayxs** [intsig171/SmartCodable#61]
public func toDictionary(useMappedKeys: Bool = false, options: Set<SmartEncodingOption>? = nil) -> [String: Any]? {
        return _transformToJson(self, type: Self.self, useMappedKeys: useMappedKeys, options: options)
    }

这个解析CPU飙升并且没有任何结果反馈，一直卡死在这里面

**Comment by intsig171** [comment]
方便加一下QQ群么？ 865036731

**Comment by intsig171** [comment]
可以辅助排查一下问题么？ 我这边没有iOS12的设备。方便加一下QQ群么？ 865036731

**Comment by intsig171** [comment]
SmartCodable 4.3.1 已经修复了该问题。 encode的时候iOS12系统因为api限制了最低iOS13，缺少了一个case。
