### ISSUE TITLE
能否优化支持 网络请求返回数据中另一个值code值为任意类型！！！

### ISSUE THREAD

**Issue by muyang00** [intsig171/SmartCodable#62]
![嗷嗷](https://github.com/user-attachments/assets/2727fa34-1ed7-46dc-9d80-193638baf7fd)

**Comment by intsig171** [comment]
![image](https://github.com/user-attachments/assets/060b29fe-5109-4fd5-abaa-8d3e5bdfddf6)
![image](https://github.com/user-attachments/assets/dcb7b2e7-7bf2-4a4e-9209-5e17d2a9e157)
