### ISSUE TITLE
Apple Customer Privacy Policy

### ISSUE THREAD

**Issue by AJ-song** [intsig171/SmartCodable#63]
The apple Privacy policy requires a list of privacy items that you want to add to the project, otherwise a warning will be issued during the review

**Comment by intsig171** [comment]
如果有需要，我可以支持它。但是SmartCodable没有使用任何跟隐私相关的。并且我也没收到警告信息。 你可以提供它么？ 如果可以请加QQ群： 865036731

**Comment by AJ-song** [comment]
It's easy to download from other third-party projects, such as MJRefresh

**Comment by intsig171** [comment]
我的意思是SmartCodable没有使用任何涉及隐私的api，不应该收到警告。这一点也从多个使用者证实过。 你可以同步一下你遇到的警告信息么?

**Comment by faimin** [comment]
[https://developer.apple.com/cn/support/third-party-SDK-requirements/](https://developer.apple.com/cn/support/third-party-SDK-requirements/) Only these SDKs have requirements, the others do not have strict requirements.  @AJ-song

**Comment by AJ-song** [comment]
OK, thank you. @faimin
