### ISSUE TITLE
是否可以支持模型设置默认值呢？

### ISSUE THREAD

**Issue by pegboggs** [intsig171/SmartCodable#7]
是否可以支持模型设置默认值呢？当解析失败，直接使用默认值

**Comment by intsig171** [comment]
我正在尝试支持。

**Comment by intsig171** [comment]
目前正在测试，预计会在V3.0.0版本上支持。

**Comment by intsig171** [comment]
支持代码已经提测。 目前已经在develop分支上发布了V3.0.1-beta版本公测。 欢迎下载测试，支持公测。
