### ISSUE TITLE
缺键状态的错误提示问题

### ISSUE THREAD

**Issue by ET-LINK** [intsig171/SmartCodable#8]
对于很多JSON框架来说, 发缺少键的JSON是常态, 之前用HandyJSON时, 所有属性都是设置为(?)可选类型, decode默认无键为nil, encode也会在值解包为nil时发送缺键的JSON
所以能不能把无键的提示从error降级到debug

**Comment by intsig171** [comment]
明白你的意思。 

在Swift的Codable解析中，遇到这三种类型均为解析失败：
1. key不存在
2. 值为null
3. 值类型错误

此时的主角应该是解析方（就是我们的decoder），从这个角度来看，定义为error层级是合理的。

目前提供两种方法：
1. 如果这种情况很多，可以关闭log日志。
2. 为了解决你的问题，我考虑在error级，再做一个关联值。

我考虑一下可行性。可以加 QQ 群了解进度。

**Comment by ET-LINK** [comment]
感谢解答
